# Generated by Django 5.0.7 on 2024-07-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee_table',
        ),
    ]
